### ISSUE TITLE
能否提供一个思路合并相同且连续的课程，并居中显示文字

### ISSUE THREAD

**Issue by gendseo** [st1ven/WeApp-timeTable#4]
例如合并下图相同且连续的课程，四行文字只居中显示一行
![image](https://user-images.githubusercontent.com/27917862/66227081-f8214880-e70e-11e9-8713-4cb4cec7276b.png)
能否提供一个思路或者实现

**Comment by st1ven** [comment]
绝对定位，计算偏移量，目前最新的文经课表小程序已经实现此功能，github已经停止维护
